name: "Création d'une nouvelle release"
'on':
  release:
    types:
      - published
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .env file
        id: dotenv
        uses: timheuer/base64-to-file@v1
        with:
          fileName: ".env"
          encodedString: ${{ secrets.DOTENV_FILE }}

      - name: Move .env into project
        run: |
          mv ${{ steps.dotenv.outputs.filePath }} ./

      - name: Build
        run: npm ci && npm run build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLICKERNUXT }}'
          channelId: live
          projectId: clickernuxt
